on:
    pull_request:
        types:
            - closed

jobs:
    if_merged:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Bump beta version
          working-directory: ./
          run: ./.github/workflows/bump_version.sh ./package version.txt
        - name: Commit version
          run: |
            git config --global user.name 'Test Bot'
            git config --global user.email 'test-bot@users.noreply.github.com'
            git commit -am "Automated report"
            git push
